### ISSUE TITLE
New upstream version (2.0.0)

### ISSUE THREAD

**Issue by ProjectSynchro** [flathub/app.ytmdesktop.ytmdesktop#3]
See: https://github.com/ytmdesktop/ytmdesktop/releases/tag/v2.0.0

Looks like the project has been rewritten, and seems to perform and function a lot better than the 1.x releases.

**Comment by ProjectSynchro** [comment]
It looks like this project has been wiped off the face of the internet, I haven't found anything on Github related to it, and their site is pointing to their github page.

Does anyone know what happened here?

**Comment by Blackcatmaxy** [comment]
Just went down a similar rabbithole, likely some DMCA thing but another repo can be found here? https://github.com/Venipa/ytmdesktop2

**Comment by ProjectSynchro** [comment]
> Just went down a similar rabbithole, likely some DMCA thing but another repo can be found here? https://github.com/Venipa/ytmdesktop2

I don't think it's DMCA related, as their repo isn't on the Github DMCA list, most likely the project imploded due to a lack of proper governance being set up, and some disagreements between developers. It does happen from time to time with some of these smaller projects unfortunately.

**Comment by Alipoodle** [comment]
As mentioned we weren't DMCAed, we are simply waiting on GitHub to set our account to public again after a member's account was comparmised. 
![image](https://github.com/flathub/app.ytmdesktop.ytmdesktop/assets/17199186/66ae2b43-89ad-41b6-aaa1-a87e4cc5cc19)


Otherwise Thank you for raising this as it is on our list to get a Flatpak version working, especially with the recent rise of the Steam Deck which has easy access to the Flatpak store.

**Comment by Lunarequest** [comment]
hi, for some reason i didn't get any notifications on this repo. I'm really sorry for the delay. The issue with electronforge is that it is basically impossible to run offline. This means that we can not use it in the traditional way to build flatpaks. [@ElectronForge/maker-flatpak](https://www.electronforge.io/config/makers/flatpak) produces a flatpak bundle that can be distributed separately and AFAIK it isn't possible to submit it to flathub. Today evening I'll look into switching to extracting the appimage and using it instead

**Comment by ProjectSynchro** [comment]
I've gone ahead and updated the flatpak to pull from the upstream binary packages. As mentioned, the build system not really allowing for offline builds to work (I'm not a javascript toolchain expert, so I'm not fully sure why) puts a bit of a block on the ability to build from source.

That said, since both arm64 and amd64 packages are being shipped, any arm64 users using Flatpak won't be affected by this change.

If this Flatpak were to be verified by one of you folks upstream @Alipoodle automerging updates could also be configured, which would improve how easily it is to maintain this repository. 

I go into some more detail about the changes required here: https://github.com/flathub/app.ytmdesktop.ytmdesktop/pull/4

**Comment by ProjectSynchro** [comment]
This is implemented now as of #4 being merged
